### ISSUE TITLE
A bug to my Mac M1 

### ISSUE THREAD

**Issue by lamhuytran** [BLKSerene/Wordless#24] opened 2022-12-12 17:40 UTC
**Describe the bug**
i just want to upload a file in order to run the app but it said it has fatal error and freeze immediately

**To Reproduce**
1. Go to file
2. Click on open file
3. Scroll down to add file

**Expected behavior**
please fix it as soon as possible

**Screenshots**
<img width="1440" alt="Screen Shot 2022-12-13 at 00 38 36" src="https://user-images.githubusercontent.com/120409112/207115372-61e65aec-d86d-41d1-b8c5-a24e1ff674e8.png">

**Environment information**
 - Operating System: [e.g. Windows 11 x64, macOS Monterey 12.6, Ubuntu 22.04 x64]
 - Wordless Version: [e.g. 2.3.0]

**Additional context**

**Comment by BLKSerene** [comment] 2022-12-12 17:47
Please try version 3.0.0. The bug might have been fixed in the latest version.

**Comment by lamhuytran** [comment] 2022-12-12 17:49
I’m currently launching on that version right now, unfortunately it still
occurs

**Comment by BLKSerene** [comment] 2022-12-12 17:51
Please copy and paste the error messages here.

**Comment by lamhuytran** [comment] 2022-12-12 17:56
https://drive.google.com/file/d/1iurZAiBBdgbAvQhs-qJC0J1erUPvM1Lx/view?usp=sharing

I did record it here, hope it might help

**Comment by BLKSerene** [comment] 2022-12-12 18:57
When a fatal error occurred, there should be a dialog prompted out which would tell you where the problem is.
Maybe that dialog is not raised to top on macOS for some reasons and is put under other windows, try switching through the Wordless icon on the taskbar.
Or, would you mind sending me your corpus file for analysis? For example, through Google drive link.

**Comment by BLKSerene** [comment] 2022-12-12 19:07
And I noticed that you are trying to import a docx Word document file, then there is a high chance that the problem is related to the 3rd-party library `python-docx` which is used by `Wordless` to process .docx files. I've received similar feedback from other users, but unfortunately, this library has been unmaintained for a long time, which means that this bug would not be fixed even if I raise the issue to the authors.

Anyway, importing non-txt files (.docx, .xlsx, .pdf) is only provided as a convenient function to users, but it is **NOT RECOMMENDED** to directly import .docx or .pdf files. Under the hood, `Wordless` would try converting these rich texts and try removing unrelated formatting things for you, which of course would not work as you expect. So, the recommended way is that you convert the .docx file to .txt file and decide by yourself which part of the .docx should be discarded (e.g. headers, footers, pictures, tables) and then import the .txt file into `Wordless`. Then everything should be OK.

**Comment by lamhuytran** [comment] 2022-12-13 04:32
Unfortunately, it still happens the same when i converted it into .txt file, i will send the file right here to you to check, hope it would help!
https://drive.google.com/file/d/1UxXluMAIppk1SU-8PI4zvCzHZQZeHu_V/view?usp=sharing

**Comment by BLKSerene** [comment] 2022-12-13 04:54
By using `Wordless` 3.0.0, the file you've sent me could be successfully added and opened (tested on Windows 11 / OS X 10.9 / macOS 12). So, I could not reproduce this issue, could you please re-verity and check again? (e.g. The file you sent me is encoded in UTF-8 without BOM, which is good for compatibility, but what about your original corpus file?)

If the issue still exists, you need to provide the detailed error messages for me to look into it.

**Closed** 2022-12-13 14:34 UTC

**Comment by BLKSerene** [comment] 2023-08-18 02:34
Just a note here: Wordless 3.3.0 has been released. It fixes a problem that some dialogs (e.g. the fatal error dialog) do not stay on top of the main window of Wordless so that the user could not see the error message or close the window on macOS (so it looks like that program just freezes or hangs forever).
